name: Build Daydream API

on:
  push:
    branches: [ ver/1.16.5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.m2
            ./Paper
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-daydream

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Action"
 
      - name: Run script
        run: |
         chmod -R +x scripts && chmod +x ./daydream
         ./daydream patch
  
      - name : Build with Maven
        run: |
         ./daydream build

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"

          git-release-bot-name: "Daydream Release Bot"
          git-release-bot-email: "release-bot@example.com"

          maven-project-folder: ./Daydream-API
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}