name: Build Daydream API (1.19)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Action"
  
      - name : Build with Gradle
        run: |
         ./gradlew applyApiPatches --no-daemon
         ./gradlew build --no-daemon
         
      - name: Generate Javadoc
        run: |
         cd Daydream-API
         ../gradlew javadoc --no-daemon

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: Daydream-API/build/docs/javadoc

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToMavenRepository
        env:
          DEPLOY_ID: ${{ secrets.DEPLOY_ID }}
          DEPLOY_PW: ${{ secrets.DEPLOY_PW }}
