name: Publish daydream-api to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.m2
            ./Paper
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-daydream

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Actions"

      - name: Run script
        run: |
         chmod -R +x scripts && chmod +x ./daydream
         ./daydream patch

      - name: Publish package
        run: |
         cd Daydream-API/
         mvn -B javadoc:jar source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
