name: Publish daydream-api to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Actions"

      - name: Run script
        run: |
         chmod -R +x scripts && chmod +x ./daydream
         ./daydream patch

      - name: Publish package
        run: mvn -B javadoc:jar source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
