name: Build Daydream API (1.16)

on:
  push:
    branches: [ ver/1.16.5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '~/.m2'
          key: ${{ runner.os }}-daydream

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Setup git config
        run: |
         git config --global user.email "no-reply@github.com"
         git config --global user.name "Github Action"
  
      - name : Build with Maven
        run: |
         chmod -R +x scripts && chmod +x ./daydream
         ./daydream patch && ./daydream build